# Generated by Django 2.1.3 on 2018-12-03 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20181203_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.City'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='description',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cinema',
            name='name',
            field=models.CharField(default='--Empty--', max_length=255),
        ),
        migrations.AddField(
            model_name='cinema',
            name='votes',
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='cinema',
            name='votes_number',
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='cinema',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
