# Generated by Django 2.1.3 on 2018-12-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20181203_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='lat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cinema',
            name='lon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
