# Generated by Django 2.1.3 on 2018-12-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20181203_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='rows',
            field=models.SmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='cinema',
            name='seats',
            field=models.SmallIntegerField(default=50),
        ),
    ]
