# Generated by Django 2.1.3 on 2018-12-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20181204_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('premiere', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('poster', models.CharField(max_length=255)),
                ('votes', models.BigIntegerField(default=0, editable=False)),
                ('votes_number', models.BigIntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'film',
                'verbose_name_plural': 'films',
            },
        ),
    ]
