# Generated by Django 2.1.3 on 2018-12-04 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_film'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rows', models.SmallIntegerField(default=5)),
                ('seats', models.SmallIntegerField(default=50)),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(auto_now=True)),
                ('end_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'session',
                'verbose_name_plural': 'sessions',
            },
        ),
        migrations.RemoveField(
            model_name='cinema',
            name='rows',
        ),
        migrations.RemoveField(
            model_name='cinema',
            name='seats',
        ),
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.FileField(upload_to='films'),
        ),
        migrations.AddField(
            model_name='session',
            name='film',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.Film'),
        ),
        migrations.AddField(
            model_name='session',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Hall'),
        ),
        migrations.AddField(
            model_name='hall',
            name='cinema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Cinema'),
        ),
    ]
