# Generated by Django 2.1.3 on 2018-12-08 00:14

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_auto_20181208_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/uploads/posters'), upload_to='posters'),
        ),
    ]
