# Generated by Django 2.1.3 on 2018-12-08 00:17

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_auto_20181208_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/home/nurik/Документы/work/python/ticketBooking/ticketbooking/uploads'), upload_to='posters'),
        ),
    ]
