# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CountriesAndCities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
                ('votes', models.PositiveIntegerField()),
                ('website', models.URLField()),
                ('lat', models.CharField(max_length=255)),
                ('lon', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CountriesAndCities.City')),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cinema_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cinemas.Cinema')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.SmallIntegerField()),
                ('col', models.SmallIntegerField()),
                ('num', models.SmallIntegerField()),
                ('hall_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cinemas.Hall')),
            ],
        ),
    ]
