# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinemas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='lat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='lon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='rating',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='votes',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
