# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cinemas', '0002_auto_20181128_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinema',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='hall',
            old_name='cinema_id',
            new_name='cinema',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='hall_id',
            new_name='hall',
        ),
    ]
