# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinemas', '0003_auto_20181128_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='hall',
        ),
        migrations.AddField(
            model_name='hall',
            name='seats',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
